#!/bin/bash

# Set the CONFIGURATIONS environment variable
export CONFIGURATIONS=$(pwd)/configurations/

# Main switch for handling different commands
case $1 in 
    "test")
        case $2 in
            "local")
                mh up msm
                mh tail msm
                rm -rf ./docs/
                mkdir -p ./docs/
                mv ./configurations/openApi/* ./docs/
                ;;
            "container")
                docker build --tag ghcr.io/agile-learning-institute/mentorhub-msm:latest .
                mh up mongodb
                mh tail mentorhub-mongomsm
                ;;
            *)
                echo "Usage: msm test [local | container]"
                exit 1
                ;;
        esac
        ;;

    *)
        echo "Usage: msm test [local | container]"
        ;;
esac
